// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNxFzJqwHYSK9B-vFMDkfAIS6S6ZMnX6I',
    appId: '1:1011616670640:web:2ac36edf1769eeb154ac75',
    messagingSenderId: '1011616670640',
    projectId: 'ekantin22',
    authDomain: 'ekantin22.firebaseapp.com',
    storageBucket: 'ekantin22.appspot.com',
    measurementId: 'G-F8XZMJM3T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMusBvFrDEJlrH6ZQgfSF5KBI-L98zDY',
    appId: '1:1011616670640:android:7351d3a4ea9f8a7454ac75',
    messagingSenderId: '1011616670640',
    projectId: 'ekantin22',
    storageBucket: 'ekantin22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC471WXyye8un8qEHfEs8ZKGsDcyD1kn8w',
    appId: '1:1011616670640:ios:e8670975e309431054ac75',
    messagingSenderId: '1011616670640',
    projectId: 'ekantin22',
    storageBucket: 'ekantin22.appspot.com',
    iosBundleId: 'com.example.eKantin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC471WXyye8un8qEHfEs8ZKGsDcyD1kn8w',
    appId: '1:1011616670640:ios:e3c003c1dbacb16a54ac75',
    messagingSenderId: '1011616670640',
    projectId: 'ekantin22',
    storageBucket: 'ekantin22.appspot.com',
    iosBundleId: 'com.example.eKantin.RunnerTests',
  );
}
